name: User actions

on: push

jobs:

  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run something
        run: echo "Job1 is running"

  job2:
    runs-on: ubuntu-latest

    needs: job1   # 👈 IMPORTANT (dependency)

    steps:
      - name: Run after job1
        run: echo "Job2 runs only if Job1 succeeds"
